networks:
  nginx-proxy:
    name: nginx-proxy
    external: true

services:
  ar-smartcore:
    container_name: ar-smartcore
    build: .
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=ar.smartcore.pe
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=ar.smartcore.pe
      - LETSENCRYPT_EMAIL=jcanahuirev@gmail.com
    networks:
      - nginx-proxy
